#!/usr/bin/env bash
# be-quiet -- Check if logging is suppressed by $DEEPDIVE_LOGLVL
##
# > be-quiet [+-ADJUSTMENT]
# Use positive ADJUSTMENT if the caller is thought to be handling a subtask.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
(( DEEPDIVE_LOGLVL += 1 - $SHLVL - ${1:-0} ))
[[ $DEEPDIVE_LOGLVL -lt 0 ]]
