#!/usr/bin/env bash
# deepdive-env -- Runs commands inside DeepDive's environment
# > deepdive env [COMMAND [ARG]...]
##
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-05-10
set -eu

[ $# -gt 0 ] || set -- bash --norc -i

exec "$@"
