#!/usr/bin/env bash
# deepdive-hack -- run commands inside deepdive's environment
# > deepdive hack [COMMAND [ARG]...]
##
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-05-10
set -eu

[ $# -gt 0 ] || set -- bash --norc -i

exec "$@"
