#!/usr/bin/env bash
# deepdive-sql -- Runs a SQL query against the database for the DeepDive application
# > deepdive sql
# Starts a SQL prompt for the underlying database.
#
# > deepdive sql query "SELECT ..."
# > deepdive sql execute "INSERT ..."
# Runs a given SQL query or update statement against the underlying database
# and prints the result in TSV format.
##
set -eu

# find the current application
APP_HOME=$(find-deepdive-app)
export APP_HOME
cd "$APP_HOME"

# parse database settings
. load-db-driver.sh

# process optional first SQL argument
if [[ $# -gt 0 ]]; then
    sql=$1; shift
    case $sql in
        query|execute)
            # there could be a mode argument we recognize, followed by the SQL
            sql_mode=$sql
            if [[ $# -gt 0 ]]; then
                sql=$1; shift
            else
                error "Missing SQL statement for '$sql' mode"
            fi
            ;;
        *)
            # otherwise, we just default to query mode
            sql_mode=query
    esac

    # TODO CSV format option
    # TODO HEADER option

    exec db-$sql_mode "$sql" "$@"
else
    exec db-prompt "$@"
fi
