#!/usr/bin/env bash
# parse-deepdive-app-db-url -- Parses DeepDive app's database URL and prints a
#                              shell script for setting up environment
# > cd $APP_HOME
# > eval "$(parse-deepdive-app-db-url)"
#
# $DEEPDIVE_DB_URL environment variable has precedence over the db.url file in
# the DeepDive application.
##
set -eu

# parse URL for database
url=${1:-${DEEPDIVE_DB_URL:-$(cat db.url)}}

# recognize the database type from the URL scheme
dbtype=${url%%://*}

# place the driver on PATH
PATH="$DEEPDIVE_HOME"/shell/driver."$dbtype":"$PATH"
# make sure all operations are defined
for op in parse init update query
do type db-$op &>/dev/null || error "db-$op operation not available for $dbtype"
done

# default environment setup script
echo "DEEPDIVE_DB_URL=${url}"
echo 'PATH="$DEEPDIVE_HOME"/shell/driver.'"${dbtype}"':"$PATH"'
echo "export DEEPDIVE_DB_URL PATH"

# parse the URL and print necessary environment setup script
db-parse $url
