#!/usr/bin/env bash
# parse-deepdive-app-db-url -- Parses DeepDive app's database URL and prints a
#                              shell script for setting up environment
# > cd $APP_HOME
# > eval "$(parse-deepdive-app-db-url)"
#
# $DEEPDIVE_DB_URL environment variable has precedence over the db.url file in
# the DeepDive application.
##
set -eu

# parse URL for database
url=${1:-${DEEPDIVE_DB_URL:-$(cat db.url)}}

parse_url() {
    local url=$1
    dbtype=${url%%://*}
    url_without_scheme=${url#*://}  # strip URL scheme
    rest=${url_without_scheme#*/}
    user_password_host_port=${url_without_scheme%%/*}
    host_port=${user_password_host_port#*@}
    user_password=${user_password_host_port%$host_port}
    user_password=${user_password%@}
    host=${host_port%:*}
    port=${host_port#$host}
    port=${port#:}
    user=${user_password%:*}
    password=${user_password#$user}
    password=${password#:}
    dbname=${rest}  # TODO do we need to strip any parameters from the rest of the URL?
}

case $url in
    postgresql://*/*|postgresql-xl://*/*|greenplum://*/*)
        parse_url $url
        # map to environment variables for psql
        echo "DBTYPE=postgresql"
        echo "DBVARIANT=${dbtype}"
        echo "PGHOST=${host}"
        echo "PGPORT=${port:-5432}"
        echo "PGUSER=${user:-$USER}"
        echo "PGPASSWORD=${password}"
        echo "DBNAME=${dbname}"
        echo "export PGHOST PGPORT PGUSER PGPASSWORD DBNAME"
        ;;

    mysql://*/*|mysqlcluster://*/*)
        parse_url $url
        # map to environment variables for psql
        echo "DBTYPE=mysql"
        echo "DBVARIANT=${dbtype}"
        echo "DBHOST=${host}"
        echo "DBPORT=${port:-3306}"
        echo "DBUSER=${user:-$USER}"
        echo "DBPASSWORD=${password}"
        echo "DBNAME=${dbname}"
        echo "export DBHOST DBPORT DBUSER DBPASSWORD DBNAME"
        ;;

    *)
        error "$url: Unrecognized database URL"
esac
echo "DBURL=${url}"

