#!/usr/bin/env bash
# verbosity-isnt -- Check if $DEEPDIVE_LOGLVL is in range
#
# > verbosity-isnt LEVEL...
##
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-03-08
(( DEEPDIVE_LOGLVL += 1 - $SHLVL ))
for l; do [[ $DEEPDIVE_LOGLVL -ne $l ]] || exit 1; done
exit 0
