#!/usr/bin/env bash
# db-parse -- Parses URL for PostgreSQL database set up for a DeepDive application
# > db-parse "$url"
set -eu

. parse-url.sh "$@"

# default values
: ${user:=$USER} ${port:=5432}

# map to environment variables for psql
echo "DBTYPE=postgresql"
# TODO proper escaping of rhs
echo "DBVARIANT=${dbtype}"
echo "DBHOST=${host}"
echo "DBPORT=${port}"
echo "DBUSER=${user}"
echo "DBPASSWORD='${password:-${PGPASSWORD:-}}'"
echo "DBNAME=${dbname}"
echo "export DBHOST DBPORT DBUSER DBPASSWORD DBNAME"

# more variables for Scala application.conf
echo "DEEPDIVE_JDBC_DRIVER=org.postgresql.Driver"
if [ ${ssl} = "true" ]; then
    echo "DEEPDIVE_JDBC_URL=jdbc:postgresql://$host${port:+:$port}/$dbname?ssl=true\&sslfactory=org.postgresql.ssl.NonValidatingFactory"
else
    echo "DEEPDIVE_JDBC_URL=jdbc:postgresql://$host${port:+:$port}/$dbname" 
fi
echo "export DEEPDIVE_JDBC_DRIVER DEEPDIVE_JDBC_URL"

# XXX several environment variables for legacy apps
echo "PGHOST=${host}"
echo "PGPORT=${port}"
echo "PGUSER=${user}"
echo "PGPASSWORD=\$DBPASSWORD"
if [ ${ssl} = "true"  ]; then
    echo "PGSSLMODE=require"
else
    echo "PGSSLMODE=disable"
fi
echo "export PGHOST PGPORT PGUSER PGPASSWORD PGSSLMODE"
