#!/usr/bin/env bash
# db-parse -- Parses URL for PostgreSQL database set up for a DeepDive application
# > db-parse "$url"
set -eu

. parse-url.sh "$@"

# map to environment variables for psql
echo "DBTYPE=postgresql"
echo "DBVARIANT=${dbtype}"
echo "PGHOST=${host}"
echo "PGPORT=${port:-5432}"
echo "PGUSER=${user:-$USER}"
echo "PGPASSWORD=${password}"
echo "DBNAME=${dbname}"
echo "export PGHOST PGPORT PGUSER PGPASSWORD DBNAME"
