#!/usr/bin/env bash
# db-update -- Executes a given SQL update query against the PostgreSQL database configured for a DeepDive application
# > eval "$(db-parse "$url")"
# > db-update SQL
##
set -eu

sql=${1:?No SQL given}; shift

exec db-prompt -c "$sql" "$@"
