#!/usr/bin/env bash
# db-parse -- Parses URL for MySQL database set up for a DeepDive application
# > db-parse "$url"
set -eu

. parse-url.sh "$@"

# map to environment variables for psql
echo "DBTYPE=mysql"
echo "DBVARIANT=${dbtype}"
echo "DBHOST=${host}"
echo "DBPORT=${port:-3306}"
echo "DBUSER=${user:-$USER}"
echo "DBPASSWORD=${password}"
echo "DBNAME=${dbname}"
echo "export DBHOST DBPORT DBUSER DBPASSWORD DBNAME"

