// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InferenceResult.proto

package org.deepdive.serialization;

public final class InferenceResultProtos {
  private InferenceResultProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WeightInferenceResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 id = 1;
    /**
     * <code>required uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     */
    long getId();

    // required double value = 2;
    /**
     * <code>required double value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required double value = 2;</code>
     */
    double getValue();
  }
  /**
   * Protobuf type {@code deepdive.WeightInferenceResult}
   */
  public static final class WeightInferenceResult extends
      com.google.protobuf.GeneratedMessage
      implements WeightInferenceResultOrBuilder {
    // Use WeightInferenceResult.newBuilder() to construct.
    private WeightInferenceResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WeightInferenceResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WeightInferenceResult defaultInstance;
    public static WeightInferenceResult getDefaultInstance() {
      return defaultInstance;
    }

    public WeightInferenceResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WeightInferenceResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              value_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_WeightInferenceResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_WeightInferenceResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult.class, org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult.Builder.class);
    }

    public static com.google.protobuf.Parser<WeightInferenceResult> PARSER =
        new com.google.protobuf.AbstractParser<WeightInferenceResult>() {
      public WeightInferenceResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WeightInferenceResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WeightInferenceResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // required double value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>required double value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double value = 2;</code>
     */
    public double getValue() {
      return value_;
    }

    private void initFields() {
      id_ = 0L;
      value_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code deepdive.WeightInferenceResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.deepdive.serialization.InferenceResultProtos.WeightInferenceResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_WeightInferenceResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_WeightInferenceResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult.class, org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult.Builder.class);
      }

      // Construct using org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_WeightInferenceResult_descriptor;
      }

      public org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult getDefaultInstanceForType() {
        return org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult.getDefaultInstance();
      }

      public org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult build() {
        org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult buildPartial() {
        org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult result = new org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult) {
          return mergeFrom((org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult other) {
        if (other == org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.deepdive.serialization.InferenceResultProtos.WeightInferenceResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 id = 1;
      private long id_ ;
      /**
       * <code>required uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required double value = 2;
      private double value_ ;
      /**
       * <code>required double value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>required double value = 2;</code>
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:deepdive.WeightInferenceResult)
    }

    static {
      defaultInstance = new WeightInferenceResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:deepdive.WeightInferenceResult)
  }

  public interface VariableInferenceResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 id = 1;
    /**
     * <code>required uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     */
    long getId();

    // optional uint64 category = 2;
    /**
     * <code>optional uint64 category = 2;</code>
     */
    boolean hasCategory();
    /**
     * <code>optional uint64 category = 2;</code>
     */
    long getCategory();

    // required double expectation = 3;
    /**
     * <code>required double expectation = 3;</code>
     */
    boolean hasExpectation();
    /**
     * <code>required double expectation = 3;</code>
     */
    double getExpectation();
  }
  /**
   * Protobuf type {@code deepdive.VariableInferenceResult}
   */
  public static final class VariableInferenceResult extends
      com.google.protobuf.GeneratedMessage
      implements VariableInferenceResultOrBuilder {
    // Use VariableInferenceResult.newBuilder() to construct.
    private VariableInferenceResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VariableInferenceResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VariableInferenceResult defaultInstance;
    public static VariableInferenceResult getDefaultInstance() {
      return defaultInstance;
    }

    public VariableInferenceResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VariableInferenceResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              category_ = input.readUInt64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              expectation_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_VariableInferenceResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_VariableInferenceResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult.class, org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult.Builder.class);
    }

    public static com.google.protobuf.Parser<VariableInferenceResult> PARSER =
        new com.google.protobuf.AbstractParser<VariableInferenceResult>() {
      public VariableInferenceResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VariableInferenceResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VariableInferenceResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional uint64 category = 2;
    public static final int CATEGORY_FIELD_NUMBER = 2;
    private long category_;
    /**
     * <code>optional uint64 category = 2;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 category = 2;</code>
     */
    public long getCategory() {
      return category_;
    }

    // required double expectation = 3;
    public static final int EXPECTATION_FIELD_NUMBER = 3;
    private double expectation_;
    /**
     * <code>required double expectation = 3;</code>
     */
    public boolean hasExpectation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double expectation = 3;</code>
     */
    public double getExpectation() {
      return expectation_;
    }

    private void initFields() {
      id_ = 0L;
      category_ = 0L;
      expectation_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExpectation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, category_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, expectation_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, category_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, expectation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code deepdive.VariableInferenceResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.deepdive.serialization.InferenceResultProtos.VariableInferenceResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_VariableInferenceResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_VariableInferenceResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult.class, org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult.Builder.class);
      }

      // Construct using org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        category_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        expectation_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deepdive.serialization.InferenceResultProtos.internal_static_deepdive_VariableInferenceResult_descriptor;
      }

      public org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult getDefaultInstanceForType() {
        return org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult.getDefaultInstance();
      }

      public org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult build() {
        org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult buildPartial() {
        org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult result = new org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.category_ = category_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.expectation_ = expectation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult) {
          return mergeFrom((org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult other) {
        if (other == org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCategory()) {
          setCategory(other.getCategory());
        }
        if (other.hasExpectation()) {
          setExpectation(other.getExpectation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasExpectation()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.deepdive.serialization.InferenceResultProtos.VariableInferenceResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 id = 1;
      private long id_ ;
      /**
       * <code>required uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 category = 2;
      private long category_ ;
      /**
       * <code>optional uint64 category = 2;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 category = 2;</code>
       */
      public long getCategory() {
        return category_;
      }
      /**
       * <code>optional uint64 category = 2;</code>
       */
      public Builder setCategory(long value) {
        bitField0_ |= 0x00000002;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 category = 2;</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000002);
        category_ = 0L;
        onChanged();
        return this;
      }

      // required double expectation = 3;
      private double expectation_ ;
      /**
       * <code>required double expectation = 3;</code>
       */
      public boolean hasExpectation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double expectation = 3;</code>
       */
      public double getExpectation() {
        return expectation_;
      }
      /**
       * <code>required double expectation = 3;</code>
       */
      public Builder setExpectation(double value) {
        bitField0_ |= 0x00000004;
        expectation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double expectation = 3;</code>
       */
      public Builder clearExpectation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        expectation_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:deepdive.VariableInferenceResult)
    }

    static {
      defaultInstance = new VariableInferenceResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:deepdive.VariableInferenceResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_deepdive_WeightInferenceResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_deepdive_WeightInferenceResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_deepdive_VariableInferenceResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_deepdive_VariableInferenceResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025InferenceResult.proto\022\010deepdive\"2\n\025Wei" +
      "ghtInferenceResult\022\n\n\002id\030\001 \002(\004\022\r\n\005value\030" +
      "\002 \002(\001\"L\n\027VariableInferenceResult\022\n\n\002id\030\001" +
      " \002(\004\022\020\n\010category\030\002 \001(\004\022\023\n\013expectation\030\003 " +
      "\002(\001B3\n\032org.deepdive.serializationB\025Infer" +
      "enceResultProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_deepdive_WeightInferenceResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_deepdive_WeightInferenceResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_deepdive_WeightInferenceResult_descriptor,
              new java.lang.String[] { "Id", "Value", });
          internal_static_deepdive_VariableInferenceResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_deepdive_VariableInferenceResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_deepdive_VariableInferenceResult_descriptor,
              new java.lang.String[] { "Id", "Category", "Expectation", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
