#!/usr/bin/env bash
# db-load -- Loads file to the PostgreSQL database configured for a DeepDive application
# > db-load TABLE FILE FORMAT
##
set -eu

table=${1:?No TABLE given}; shift
file=${1:?No FILE given}; shift
format=${1:?No FORMAT given}; shift

copy_option=
case $format in
    tsv)
        db-execute "COPY $table FROM STDIN" < $file
        ;;
    csv)
        db-execute "COPY $table FROM STDIN CSV" < $file
        ;;
    *) error "$format: unsupported format by PostgreSQL driver" ;;
esac
