#!/usr/bin/env bash
# db-parse -- Parses URL for PostgreSQL database set up for a DeepDive application
# > db-parse "$url"
set -eu

. parse-url.sh "$@"

# default values
: ${user:=$USER} ${port:=5432}

# map to environment variables for psql
escape4sh export "DBTYPE=postgresql"
escape4sh export "DBVARIANT=${dbtype}"
escape4sh export "DBHOST=${host}"
escape4sh export "DBPORT=${port}"
escape4sh export "DBUSER=${user}"
escape4sh export "DBPASSWORD=${password:-${PGPASSWORD:-}}"
escape4sh export "DBNAME=${dbname}"

# more variables for Scala application.conf
escape4sh export "DEEPDIVE_JDBC_DRIVER=org.postgresql.Driver"

escape4sh export "DEEPDIVE_JDBC_URL=jdbc:postgresql://$host${port:+:$port}/$dbname$querystring"

# XXX several environment variables for legacy apps
escape4sh export "PGHOST=${host}"
escape4sh export "PGPORT=${port}"
escape4sh export "PGUSER=${user}"
echo 'export PGPASSWORD=$DBPASSWORD'
case $querystring in
    *ssl=true*) escape4sh export "PGSSLMODE=require" ;;
    *)          escape4sh export "PGSSLMODE=disable"
esac
