#!/usr/bin/env bats
# DeepDive Scala Tests for org.deepdive.test.unit.ExtractorRunnerSpec
# DO NOT EDIT -- GENERATED BY test/postgresql/update-scalatests.bats.sh

. "${BATS_TEST_DIRNAME%/scalatests}"/env.sh >&2

setup() {
    db-init
}

@test "$DBVARIANT ScalaTest org.deepdive.test.unit.ExtractorRunnerSpec" {
    java org.scalatest.tools.Runner -oDF -s org.deepdive.test.unit.ExtractorRunnerSpec
}
