#!/usr/bin/env bash
# db-load -- Loads file to the MySQL database configured for a DeepDive application
# > db-load TABLE COLUMN FORMAT [SOURCE...]
##
set -eu

[[ $# -gt 0 ]] || usage "$0" "No TABLE given"
table=$1; shift
[[ $# -gt 0 ]] || usage "$0" "No COLUMNS given"
columns=$1; shift
[[ $# -gt 0 ]] || usage "$0" "No FORMAT given"
format=$1; shift

columns=${columns:+($columns)}

# See: https://dev.mysql.com/doc/refman/5.7/en/load-data.html
case $format in
    tsv)
        cat "$@" | show_progress input_to "loading $table" -- \
            db-execute "LOAD DATA LOCAL INFILE '/dev/stdin' INTO TABLE $table
              FIELDS TERMINATED BY '\t'
              $columns
              "
        ;;
    csv)
        cat "$@" | show_progress input_to "loading $table" -- \
            db-execute "LOAD DATA LOCAL INFILE '/dev/stdin' INTO TABLE $table
              FIELDS TERMINATED BY ',' ENCLOSED BY '\"'
              LINES TERMINATED BY '\r\n'
              $columns
              "
              # TODO if header=true, "IGNORE 1 LINES"
        ;;
    *) error "$format: unsupported format by MySQL driver" ;;
esac
