#!/usr/bin/env bash
# db-prompt -- Starts a prompt for the MySQL database configured for a DeepDive application
# > eval "$(db-parse "$url")"
# > db-prompt
##
set -eu

exec mysql -h "$DBHOST" -P "$DBPORT" -u "$DBUSER" --password="$DBPASSWORD" -D "$DBNAME" --local-infile "$@"
