# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factor_graph.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='factor_graph.proto',
  package='deepdive',
  serialized_pb='\n\x12\x66\x61\x63tor_graph.proto\x12\x08\x64\x65\x65pdive\"S\n\x06Weight\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x17\n\x0cinitialValue\x18\x02 \x01(\x01:\x01\x30\x12\x0f\n\x07isFixed\x18\x03 \x02(\x08\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"\xdb\x01\n\x08Variable\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x14\n\x0cinitialValue\x18\x02 \x01(\x01\x12\x35\n\x08\x64\x61taType\x18\x03 \x02(\x0e\x32#.deepdive.Variable.VariableDataType\x12\x12\n\nisEvidence\x18\x04 \x01(\x08\x12\x13\n\x0b\x63\x61rdinality\x18\x05 \x01(\x04\x12\x11\n\tedgeCount\x18\x06 \x01(\x04\":\n\x10VariableDataType\x12\x0b\n\x07\x42OOLEAN\x10\x00\x12\x0f\n\x0bMULTINOMIAL\x10\x01\x12\x08\n\x04REAL\x10\x02\"\xbf\x01\n\x06\x46\x61\x63tor\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x10\n\x08weightId\x18\x02 \x02(\x04\x12;\n\x0e\x66\x61\x63torFunction\x18\x03 \x02(\x0e\x32#.deepdive.Factor.FactorFunctionType\x12\x11\n\tedgeCount\x18\x04 \x01(\x04\"G\n\x12\x46\x61\x63torFunctionType\x12\t\n\x05IMPLY\x10\x00\x12\x06\n\x02OR\x10\x01\x12\x07\n\x03\x41ND\x10\x02\x12\t\n\x05\x45QUAL\x10\x03\x12\n\n\x06ISTRUE\x10\x04\"]\n\tGraphEdge\x12\x12\n\nvariableId\x18\x01 \x02(\x04\x12\x10\n\x08\x66\x61\x63torId\x18\x02 \x02(\x04\x12\x10\n\x08position\x18\x03 \x02(\x04\x12\x18\n\nisPositive\x18\x04 \x01(\x08:\x04true\"\xb1\x01\n\x0b\x46\x61\x63torGraph\x12\x12\n\nnumWeights\x18\x01 \x02(\x04\x12\x14\n\x0cnumVariables\x18\x02 \x02(\x04\x12\x12\n\nnumFactors\x18\x03 \x02(\x04\x12\x10\n\x08numEdges\x18\x04 \x02(\x04\x12\x13\n\x0bweightsFile\x18\x05 \x02(\t\x12\x15\n\rvariablesFile\x18\x06 \x02(\t\x12\x13\n\x0b\x66\x61\x63torsFile\x18\x07 \x02(\t\x12\x11\n\tedgesFile\x18\x08 \x02(\t\"2\n\x15WeightInferenceResult\x12\n\n\x02id\x18\x01 \x02(\x04\x12\r\n\x05value\x18\x02 \x02(\x01\"L\n\x17VariableInferenceResult\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\x04\x12\x13\n\x0b\x65xpectation\x18\x03 \x02(\x01\x42/\n\x1aorg.deepdive.serializationB\x11\x46\x61\x63torGraphProtos')



_VARIABLE_VARIABLEDATATYPE = _descriptor.EnumDescriptor(
  name='VariableDataType',
  full_name='deepdive.Variable.VariableDataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BOOLEAN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTINOMIAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REAL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=279,
  serialized_end=337,
)

_FACTOR_FACTORFUNCTIONTYPE = _descriptor.EnumDescriptor(
  name='FactorFunctionType',
  full_name='deepdive.Factor.FactorFunctionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IMPLY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AND', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUAL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISTRUE', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=460,
  serialized_end=531,
)


_WEIGHT = _descriptor.Descriptor(
  name='Weight',
  full_name='deepdive.Weight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='deepdive.Weight.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initialValue', full_name='deepdive.Weight.initialValue', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isFixed', full_name='deepdive.Weight.isFixed', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='deepdive.Weight.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=115,
)


_VARIABLE = _descriptor.Descriptor(
  name='Variable',
  full_name='deepdive.Variable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='deepdive.Variable.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initialValue', full_name='deepdive.Variable.initialValue', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataType', full_name='deepdive.Variable.dataType', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isEvidence', full_name='deepdive.Variable.isEvidence', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cardinality', full_name='deepdive.Variable.cardinality', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edgeCount', full_name='deepdive.Variable.edgeCount', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VARIABLE_VARIABLEDATATYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=118,
  serialized_end=337,
)


_FACTOR = _descriptor.Descriptor(
  name='Factor',
  full_name='deepdive.Factor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='deepdive.Factor.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weightId', full_name='deepdive.Factor.weightId', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factorFunction', full_name='deepdive.Factor.factorFunction', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edgeCount', full_name='deepdive.Factor.edgeCount', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FACTOR_FACTORFUNCTIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=340,
  serialized_end=531,
)


_GRAPHEDGE = _descriptor.Descriptor(
  name='GraphEdge',
  full_name='deepdive.GraphEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variableId', full_name='deepdive.GraphEdge.variableId', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factorId', full_name='deepdive.GraphEdge.factorId', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='deepdive.GraphEdge.position', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isPositive', full_name='deepdive.GraphEdge.isPositive', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=533,
  serialized_end=626,
)


_FACTORGRAPH = _descriptor.Descriptor(
  name='FactorGraph',
  full_name='deepdive.FactorGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numWeights', full_name='deepdive.FactorGraph.numWeights', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numVariables', full_name='deepdive.FactorGraph.numVariables', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numFactors', full_name='deepdive.FactorGraph.numFactors', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numEdges', full_name='deepdive.FactorGraph.numEdges', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weightsFile', full_name='deepdive.FactorGraph.weightsFile', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variablesFile', full_name='deepdive.FactorGraph.variablesFile', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factorsFile', full_name='deepdive.FactorGraph.factorsFile', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edgesFile', full_name='deepdive.FactorGraph.edgesFile', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=629,
  serialized_end=806,
)


_WEIGHTINFERENCERESULT = _descriptor.Descriptor(
  name='WeightInferenceResult',
  full_name='deepdive.WeightInferenceResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='deepdive.WeightInferenceResult.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='deepdive.WeightInferenceResult.value', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=808,
  serialized_end=858,
)


_VARIABLEINFERENCERESULT = _descriptor.Descriptor(
  name='VariableInferenceResult',
  full_name='deepdive.VariableInferenceResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='deepdive.VariableInferenceResult.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='category', full_name='deepdive.VariableInferenceResult.category', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expectation', full_name='deepdive.VariableInferenceResult.expectation', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=860,
  serialized_end=936,
)

_VARIABLE.fields_by_name['dataType'].enum_type = _VARIABLE_VARIABLEDATATYPE
_VARIABLE_VARIABLEDATATYPE.containing_type = _VARIABLE;
_FACTOR.fields_by_name['factorFunction'].enum_type = _FACTOR_FACTORFUNCTIONTYPE
_FACTOR_FACTORFUNCTIONTYPE.containing_type = _FACTOR;
DESCRIPTOR.message_types_by_name['Weight'] = _WEIGHT
DESCRIPTOR.message_types_by_name['Variable'] = _VARIABLE
DESCRIPTOR.message_types_by_name['Factor'] = _FACTOR
DESCRIPTOR.message_types_by_name['GraphEdge'] = _GRAPHEDGE
DESCRIPTOR.message_types_by_name['FactorGraph'] = _FACTORGRAPH
DESCRIPTOR.message_types_by_name['WeightInferenceResult'] = _WEIGHTINFERENCERESULT
DESCRIPTOR.message_types_by_name['VariableInferenceResult'] = _VARIABLEINFERENCERESULT

class Weight(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEIGHT

  # @@protoc_insertion_point(class_scope:deepdive.Weight)

class Variable(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VARIABLE

  # @@protoc_insertion_point(class_scope:deepdive.Variable)

class Factor(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FACTOR

  # @@protoc_insertion_point(class_scope:deepdive.Factor)

class GraphEdge(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GRAPHEDGE

  # @@protoc_insertion_point(class_scope:deepdive.GraphEdge)

class FactorGraph(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FACTORGRAPH

  # @@protoc_insertion_point(class_scope:deepdive.FactorGraph)

class WeightInferenceResult(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEIGHTINFERENCERESULT

  # @@protoc_insertion_point(class_scope:deepdive.WeightInferenceResult)

class VariableInferenceResult(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VARIABLEINFERENCERESULT

  # @@protoc_insertion_point(class_scope:deepdive.VariableInferenceResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\032org.deepdive.serializationB\021FactorGraphProtos')
# @@protoc_insertion_point(module_scope)
