#!/usr/bin/env bash
# deepdive-relation -- Shows information about relations defined in a DeepDive app
#
# $ deepdive relation list
# Lists all declared relations.
#
# $ deepdive relation columns RELATION
# Lists name and type of all columns for RELATION.
##
set -euo pipefail

[[ $# -gt 0 ]] || usage "$0" "Missing mode"
Mode=$1; shift

DEEPDIVE_APP=$(find-deepdive-app)
export DEEPDIVE_APP
app-has-been-compiled
cd "$DEEPDIVE_APP"

case $Mode in
    list)
        # enumerate names of all relations
        jq -r '.deepdive_.schema.relations | keys[]' run/compiled/config.json
        ;;

    variables)
        # enumerate names of all variable relations
        jq -r '.deepdive_.schema.relations | to_entries[] |
                select(.value.variable_type) | .key' run/compiled/config.json
        ;;

    columns)
        # enumerate in COLUMN:TYPE format
        [[ $# -gt 0 ]] || usage "$0" "Missing RELATION"
        export Relation=$1; shift
        jq -e -r '
            .deepdive_.schema.relations[env.Relation] |
            if type == "null" then
                # non-existent relation
                empty
            else
                if .variable_type then
                    # variable relations have label column
                    .columns + {label:{type:"boolean", index:(.columns|length)}}
                else
                    .columns
                end |
                to_entries |
                sort_by(.value.index) |
                # output COLUMN:TYPE lines
                .[] | [.key, .value.type] | join(":")
            end
        ' run/compiled/config.json ||
            error "$Relation: No such relation"
        ;;

    *)
        usage "$0" "$Mode: Unrecognized mode"
esac
