#!/usr/bin/env bash
# ssh_with_env -- Executes a command through SSH while passing specified environment variables
# > ssh_with_env KEY[=VALUE]... -- REST
# 
# If the VALUE associated with KEY is specified, then it will be passed as specified. 
# Otherwise, KEY is expanded based on the value of that environment variable in the current
# environment. 
#
# Assumes SSH_INFO exists in the environment. 
#
# Example command:
#   ssh_with_env NUM_PROCESSES=10 -- "deepdive compute remote-status"
##
set -euo pipefail

join_expand() { 
  for k in "$@"; do
    if [[ ! -z "$k" ]]; then
      if [[ "$k" == *=* ]]; then
        echo -n "$k "
      else
        eval "echo -n \"$k=\$$k \""
      fi
    fi
  done
}

ENV_VARS=()
while [[ $# -gt 0 && $1 != "--" ]]; do
  ENV_VARS+=("$1"); shift
done
[[ ${1:-} = "--" ]] || usage "$0" "Missing -- before COMMAND"
shift
COMMAND="$@"

ssh $SSH_INFO "$(join_expand ${ENV_VARS[@]})" "$(escape4sh $COMMAND)"
