#!/usr/bin/env bash
# compile-codegen -- Generates files from the compiled code represented in JSON
##
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2015-12-05
set -euo pipefail
eval "$(jq -r '"
x=\(.path | @sh)
echo >&2 \" run/$x\"
mkdir -p \"$(dirname \"$x\")\"
echo \(.content | @sh) >\"$x\"
\(.mode | if . then "chmod \(@sh) \"$x\"" else "" end)
"')"
