#!/usr/bin/env bash
# compile-tsv_extractor -- Compiles given extractor specified in JSON into a form executable by DeepDive
set -eu

ExtractorName=$1; shift
ExtractorSpec=$1; shift

ExtractorName=$ExtractorName \
ExtractorStyle=${0##*compile-} \
jq -r <<<"$ExtractorSpec" >run.sh '
"#!/usr/bin/env bash
# \(env.ExtractorStyle)  \(env.ExtractorName)
# \(@json)
set -xeuo pipefail
cd \"$(dirname \"$0\")\"

\(.before // "")

export DEEPDIVE_CURRENT_PROCESS_NAME=\(env.ExtractorName | @sh)
export DEEPDIVE_LOAD_FORMAT=tsv

compute-execute \\
    input_sql=\(.input | @sh) \\
    command=\(.udf | @sh) \\
    output_relation=\(.output_relation | @sh) \\
    #

\(.after // "")
"
'
chmod +x run.sh
