#!/usr/bin/env bash
# compile-sql_factor -- Generates the grounding instruction for given factor specified in JSON into a form executable by DeepDive
set -eu

FactorName=$1; shift
FactorSpec=$1; shift

FactorName=$FactorName \
FactorStyle=${0##*compile-} \
jq -r <<<"$FactorSpec" >run.sh '
"#!/usr/bin/env bash
# \(env.FactorStyle)  \(env.FactorName)
# \(@json)
set -xeuo pipefail

# TODO
# deepdive sql \(.input_query | @sh)

# TODO record \(env.FactorName) in the model/ to use the when invoking deepdive.jar for the actual grounding

error \("Grounding factor \(env.FactorName) not implemented yet" | @sh)
"
'
chmod +x run.sh
