#!/usr/bin/env bash
# compile-cmd_extractor -- Compiles given extractor specified in JSON into a form executable by DeepDive
set -eu

ExtractorName=$1; shift
ExtractorSpec=$1; shift

ExtractorName=$ExtractorName \
ExtractorStyle=${0##*compile-} \
jq -r <<<"$ExtractorSpec" >run.sh '
"#!/usr/bin/env bash
# \(env.ExtractorStyle)  \(env.ExtractorName)
# \(@json)
set -euo pipefail

\(.before // "")

\(.cmd)

\(.after // "")
"
'
chmod +x run.sh
