#!/usr/bin/env bash
# compile-tsv_extractor -- Compiles given extractor specified in JSON into a form executable by DeepDive
set -eu

ExtractorName=$1; shift
ExtractorSpec=$1; shift

ExtractorName=$ExtractorName \
ExtractorStyle=${0##*compile-} \
jq -r <<<"$ExtractorSpec" >run.sh '
"#!/usr/bin/env bash
# \(env.ExtractorStyle)  \(env.ExtractorName)
# \(@json)
set -xeuo pipefail
cd \"$(dirname \"$0\")\"

\(.before // "")

deepdive sql eval \(.input | @sh) format=tsv |
show_progress \(env.ExtractorName | @sh) |
bash -c \(.udf | @sh) |
deepdive sql \("COPY \(.output_relation) FROM STDIN" | @sh)

\(.after // "")
"
'
chmod +x run.sh
