#!/usr/bin/env bash
# compile-code-piggy_extractor -- TODO Compiles piggy_extractors in the normalized JSON into code executable by the runner
exec jq '.deepdive_ as $deepdive

| .deepdive_.extraction.extractors | to_entries[]
| .value.name = .key | .value
| select(.style == "piggy_extractor")
| error("\(.name): Compilation of \(.style) unsupported")
' "$@"
