#!/usr/bin/env bash
# test-in-container -- Tests inside a Docker container with the latest build
##
set -euo pipefail
. "$(dirname "$0")"/DockerBuild.bash

# NOTE other containers, e.g., postgresql or gpdb, can be run externally, then
# their names can be passed as arguments for --link options followed by the
# normal test command, e.g.:
# $ export DOCKER_RUN_OPTS="--link foo --link bar"
# $ test-in-container  env POSTGRES=foo MONGODB=bar  make test

# default test command
[[ $# -gt 0 ]] || set -- bash -xeuc "$DOCKER_TEST_COMMAND"

tagFromGit=$(docker-tag-from-git)
dockerContainerTest+="$DOCKER_CONTAINER.$tagFromGit.test.$$"
dockerImageBranchRun=$(printf "$DOCKER_IMAGE_BRANCH_FORMAT_RUN" "$tagFromGit")
dockerImageBranchBuild=$(printf "$DOCKER_IMAGE_BRANCH_FORMAT_BUILD" "$tagFromGit")
dockerImageBranchTest=$(printf "$DOCKER_IMAGE_BRANCH_FORMAT_TEST" "$tagFromGit")
dockerImageBranchStable=$(printf "$DOCKER_IMAGE_BRANCH_FORMAT_STABLE" "$tagFromGit")

dockerImageToRunTest=$dockerImageBranchBuild

Here=$(dirname "$0")
on_exit() {
    exitStatus=$?  # keep it to preserve the test's exit status
    case $exitStatus in 0)
        docker tag "$dockerImageToRunTest" "$dockerImageBranchStable"
    esac
    docker commit "$dockerContainerTest" "$dockerImageBranchTest".$$
    docker rm -f "$dockerContainerTest"
    case $exitStatus in
        0)  verdict=PASS
            next-steps() {
                echo '# Docker image '"$DOCKER_IMAGE_LATEST_TEST"-PASS' now points to the test results'
                echo '# and '"$dockerImageBranchStable"' points to the build the tests were run.'
                echo '# Use `'"$Here"'/inspect-container` to run commands on the test results.'
            }
            ;;
        *)  verdict=FAIL
            next-steps() {
                echo '# Docker image '"$dockerImageBranchTest"'-FAIL now points to this test container.'
                echo '# Use `'"$Here"'/inspect-container` to open a shell for debugging.'
            }
    esac 2>/dev/null
    docker tag "$dockerImageBranchTest".$$ "$dockerImageBranchRun"
    docker tag "$dockerImageBranchTest".$$ "$dockerImageBranchTest"
    docker tag "$dockerImageBranchTest".$$ "$dockerImageBranchTest"-$verdict
    docker tag "$dockerImageBranchTest".$$ "$DOCKER_IMAGE_LATEST_TEST"-$verdict
    docker tag "$dockerImageBranchTest".$$ "$DOCKER_IMAGE_LATEST_TEST"
    docker rmi -f "$dockerImageBranchTest".$$
    { set +x; } 2>/dev/null
    echo '###############################################################################'
    next-steps
    echo '###############################################################################'
    exit $exitStatus
}
trap on_exit EXIT
set -x
# run tests
docker-run --name "$dockerContainerTest" -- "$dockerImageToRunTest" "$@"
