#!/usr/bin/env bash
# test-in-container-greenplum -- Tests with Greenplum container linked
##
set -euo pipefail
. "$(dirname "$0")"/config.bash

: ${DOCKER_GPNAME:=test-greenplum}
: ${GREENPLUM_USER:=gpadmin}
: ${GREENPLUM_PASSWORD:=pivotal}

# run a greenplum container
trap 'docker rm -f "$DOCKER_GPNAME"' EXIT
set -x
docker run --detach --name "$DOCKER_GPNAME" \
    --publish 5432 \
    pivotaldata/gpdb-base

# run test against it
DOCKER_RUN_OPTS="
    --link $DOCKER_GPNAME
    " \
test-in-container \
    env \
        TEST_GREENPLUM_DBHOST="$GREENPLUM_USER:$GREENPLUM_PASSWORD@$DOCKER_GPNAME" \
    /bin/sh -euc '
# FIXME greenplum client executables must be installed
make test "$@"
'
