#!/usr/bin/env bash
# test-in-container-postgres -- Tests with PostgreSQL container linked
##
set -euo pipefail
. "$(dirname "$0")"/config.bash

DOCKER_PGNAME=test-postgres
POSTGRES_PASSWORD=$RANDOM$RANDOM

# run a postgres container
trap 'docker rm -f "$DOCKER_PGNAME"' EXIT
set -x
docker run --detach --name "$DOCKER_PGNAME" \
    --env POSTGRES_USER="$USER" \
    --env POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
    postgres

# run test against it
DOCKER_RUN_OPTS="
    --link $DOCKER_PGNAME
    " \
test-in-container \
    env \
        TEST_POSTGRES_DBHOST="$USER:$POSTGRES_PASSWORD@$DOCKER_PGNAME" \
    make test "$@"
