#!/usr/bin/env bash
# db-load -- Loads file to the PostgreSQL database configured for a DeepDive application
# > db-load TABLE COLUMNS FORMAT [SOURCE...]
##
set -eu

[[ $# -gt 0 ]] || usage "$0" "No TABLE given"
table=$1; shift
[[ $# -gt 0 ]] || usage "$0" "No COLUMNS given"
columns=$1; shift
[[ $# -gt 0 ]] || usage "$0" "No FORMAT given"
format=$1; shift

table="$table${columns:+($columns)}"
case $format in
    tsv)
        i=1 nsources=$#
        for source; do
            show_progress input_to "loading $table [$i/$nsources]" -- \
            db-execute "\COPY $table FROM PSTDIN" <"$source" &
            let ++i
        done
        wait
        ;;
    csv)
        cat "$@" | show_progress input_to "loading $table" -- \
            db-execute "\COPY $table FROM PSTDIN CSV"
        ;;
    *) error "$format: unsupported format by PostgreSQL driver" ;;
esac
