#!/usr/bin/env bash
# db-unload -- Unloads a SQL query to a set of sinks
# > db-unload QUERY FORMAT SINK...
##
set -eu

[[ $# -gt 0 ]] || usage "$0" "Missing QUERY"
query=$1; shift
[[ $# -gt 0 ]] || usage "$0" "Missing FORMAT"
format=$1; shift
[[ $# -gt 0 ]] || usage "$0" "Missing SINK"

case $format in
    tsv)
        i=1 nsinks=$#
        if [[ $nsinks -gt 1 ]]; then
            case "$(tr a-z A-Z <<<"$query")" in
                *"FROM"*","*|*"JOIN"*) # if it contains joins
                    # materialize the query first
                    tmpTable="dd_unload_$(sha1sum <<<"$query" | cut -b1-40)"
                    db-create table "$tmpTable" as "$query"
                    tmpTableWasMaterialized=true
                    ;;
                *)
                    tmpTable="($query) R"
                    tmpTableWasMaterialized=false
            esac
            partition_integers $(db-query "SELECT COUNT(*) FROM $tmpTable" "$format" 0) $nsinks |
            while read limit offset end; do
                sink=$1; shift
                show_progress output_from "unloading [$i/$nsinks]" -- \
                db-query "SELECT * FROM $tmpTable LIMIT $limit OFFSET $offset" "$format" 0 >"$sink" &
                let ++i
            done
            wait
            ! $tmpTableWasMaterialized ||
                db-execute "DROP TABLE IF EXISTS $tmpTable"
        else
            sink=$1; shift
            exec show_progress output_from "unloading" -- \
                db-query "$query" "$format" 0 >"$sink"
        fi
        ;;
    *) error "$format: unsupported format by PostgreSQL driver" ;;
esac
