#!/usr/bin/env bash
# db-execute -- Executes a given SQL query against the Drill database configured for a DeepDive application
# > eval "$(db-parse "$url")"
# > db-execute SQL
##
set -eu

sql=${1:?No SQL given}; shift
sql=${sql//\"/\`}
sql=${sql//!=/<>}
sql="$( echo "$sql" | python -c 'import sys;import re;lines=sys.stdin.readlines();input="".join(lines);print(re.sub(",[\n\s]*NULL", ", CAST(NULL AS ANY)", input))' )"
if [ "$DISTRIBUTED" = true ];then
    exec sqlline -u 'jdbc:drill:schema='"$DBNAME"';zk='"$ZOOKEEPERS" -n "$DBUSER" -p "$DBPASSWORD" -f <(echo "$sql")
else
    exec sqlline -u 'jdbc:drill:schema='"$DBNAME"';zk=local' -n "$DBUSER" -p "$DBPASSWORD" -f <(echo "$sql")
fi
