#!/usr/bin/env bash
# db-execute -- Executes a given SQL query against the Drill database configured for a DeepDive application
# > eval "$(db-parse "$url")"
# > db-execute SQL
##
set -eu

sql=${1:?No SQL given}; shift
sql=${sql//\"/\`}
if [ "$DISTRIBUTED" = true ];then
    exec sqlline -u 'jdbc:drill:schema='"$DBNAME"';zk='"$ZOOKEEPERS" -n "$DBUSER" -p "$DBPASSWORD" -f <(echo "$sql")
else
    exec sqlline -u 'jdbc:drill:schema='"$DBNAME"';zk=local' -n "$DBUSER" -p "$DBPASSWORD" -f <(echo "$sql")
fi
