#!/usr/bin/env bash
# db-prompt -- Starts a prompt for the Drill database configured for a DeepDive application
# > eval "$(db-parse "$url")"
# > db-prompt
##
set -eu
exec "$CONFIGURED_DRILL_EXECUTABLE"

#PGPASSWORD="$DBPASSWORD" \
#exec psql -h "$DBHOST" -p "$DBPORT" -U "$DBUSER" -d "$DBNAME" "$@"
