#!/usr/bin/env bash
# db-prompt -- Starts a prompt for the Drill database configured for a DeepDive application
# > eval "$(db-parse "$url")"
# > db-prompt
##
set -eu

if [ "$DISTRIBUTED" = true ];then
    exec sqlline -u 'jdbc:drill:schema='"$DBNAME"';zk='"$ZOOKEEPERS" -n "$DBUSER" -p "$DBPASSWORD"
else
    exec sqlline -u 'jdbc:drill:schema='"$DBNAME"';zk=local' -n "$DBUSER" -p "$DBPASSWORD"
fi
