#!/usr/bin/env bash
# db-parse -- Parses URL for Drill database set up for a DeepDive application
# > db-parse "$url"
set -eu

. parse-url.sh "$@"

# default values
: ${user:=$USER} ${port:=5432}

# parse extra options for Drill
optionString=${querystring#\?}

IFS='&' read -r -a optionArray <<< "$optionString"
for option in "${optionArray[@]}"
do
    optionKey=${option%%=*}
    optionValue=${option#*=}
    case "$optionKey" in
        distributed)
            DISTRIBUTED="$optionValue"
            ;;
        zk)
            ZOOKEEPERS="$optionValue"
            ;;
        *)
            error "Unrecognized option for Drill: $optionKey"
            ;;
    esac
done

# embedded Drill is the default setting
echo "DISTRIBUTED=${DISTRIBUTED=false}"

# prepend main host to zookeeper string
hostString="$host"
if [ -n "$port" ];then
    hostString="$hostString:$port"
fi
if [ -z ${ZOOKEEPERS+x} ];then
    ZOOKEEPERS="$hostString"
else
    ZOOKEEPERS="$hostString,$ZOOKEEPERS"
fi
echo "ZOOKEEPERS=${ZOOKEEPERS/localhost/local}"

# map to environment variables for Drill
echo "DBTYPE=drill"
# TODO proper escaping of rhs
echo "DBVARIANT=${dbtype}"
echo "DBHOST=${host}"
echo "DBPORT=${port}"
echo "DBUSER=${user}"
echo "DBPASSWORD='${password:-${PGPASSWORD:-}}'"
echo "DBNAME=${dbname}"
echo "export DBHOST DBPORT DBUSER DBPASSWORD DBNAME"

# variables for managing Drill tables and views
echo "DRILL_WORK_DIRECTORY=$DEEPDIVE_APP/run/database/drill/$dbname"
echo "export DISTRIBUTED ZOOKEEPERS DRILL_WORK_DIRECTORY"




# more variables for Scala application.conf
echo "DEEPDIVE_JDBC_DRIVER=org.postgresql.Driver"

echo "DEEPDIVE_JDBC_URL='jdbc:postgresql://$host${port:+:$port}/$dbname$querystring'"
echo "export DEEPDIVE_JDBC_DRIVER DEEPDIVE_JDBC_URL"

# XXX several environment variables for legacy apps
# TODO Pass through $DEEPDIVE_DB_URL to Postgresql >= 9.2 since it natively supports URIs
# TODO try to translate all params in URI to environment variables or keyword=value string
# See: http://www.postgresql.org/docs/8.1/static/libpq-envars.html
# See: http://www.postgresql.org/docs/9.2/static/libpq-connect.html#LIBPQ-CONNSTRING
echo "PGHOST=${host}"
echo "PGPORT=${port}"
echo "PGUSER=${user}"
echo "PGPASSWORD=\$DBPASSWORD"
case $querystring in
    *sslmode=*)
        sslmode=${querystring#*sslmode=}; sslmode=${sslmode%&*} # FIXME this is brittle, need a proper URL querystring parsing, perhaps from ../parse-url.sh
        echo "DEEPDIVE_JDBC_URL+='&ssl=true'"
        echo "PGSSLMODE=${sslmode}" ;;
    *ssl=true*) echo "PGSSLMODE=require" ;;
    *) echo "PGSSLMODE=prefer"
esac
echo "export PGHOST PGPORT PGUSER PGPASSWORD PGSSLMODE"
