#!/usr/bin/env bash
# db-prompt -- Starts a prompt for the Drill database configured for a DeepDive application
# > eval "$(db-parse "$url")"
# > db-prompt
##
set -eu
echo EXECUTING DB-PROMPT
echo "$@"
exit 1
exec "$DRILL_EXECUTABLE" -f <(echo "$@")

#PGPASSWORD="$DBPASSWORD" \
#exec psql -h "$DBHOST" -p "$DBPORT" -U "$DBUSER" -d "$DBNAME" "$@"
