#!/usr/bin/env bash
# deepdive-do -- Runs necessary processes to get something done
# > deepdive do TARGET...
##
set -euo pipefail

targets="$*"
. resolve-args-to-do.sh
cd "$DEEPDIVE_APP"/run

if deepdive-done "$@"; then
    echo "All done at $(format_timestamp $(ls -t "$@" | head -1)):"
    echo " $targets"
    echo "To see more details, use: deepdive plan"
    echo "To redo them anyway, use: deepdive redo"
    exit 0
fi

# create a directory for running
runDir=$(date +%Y%m%d/%H%M%S.%N)
mkdir -p "$runDir"
# make sure we clean up
cleanup() {
    [[ ! RUNNING -ef "$runDir" ]] || rm -f RUNNING
}
abort() {
    [[ ! -e "$runDir" ]] || ln -sfn "$runDir" ABORTED
}
trap cleanup EXIT
trap abort ERR
ln -sfnv "$runDir" RUNNING

deepdive-plan "$@" |
# insert a filename line
sed '1 i\'$'\n''# run/'"$runDir"'/plan.sh\'$'\n' |
tee "$runDir"/plan.orig.sh >"$runDir"/plan.sh

# provide a chance to edit plan in a tty unless told not to ask
if [[ -t 0 && -t 1 && $EDITOR != true && $EDITOR != : && ${DEEPDIVE_PLAN_EDIT:-true} ]]; then
    ${VISUAL:-${EDITOR:-vi}} "$runDir"/plan.sh &&
    [[ "$runDir"/plan.sh -nt "$runDir"/plan.orig.sh ]] || {
        cleanup
        rm -rf "$runDir"
        error "Canceled execution"
    }
fi

# remove original unless modified
! diff -q "$runDir"/plan{,.orig}.sh || rm -f "$runDir"/plan.orig.sh

# run it
DEEPDIVE_ERROR_PREFIX="[ERROR] "  # prefixing error messages in logs
: ${DEEPDIVE_PROGRESS_FD:=3}  # file descriptor to pass stderr down to our show_progress(1) command
DEEPDIVE_APP=$(cd .. && pwd -P)
APP_HOME=$DEEPDIVE_APP # XXX legacy
export DEEPDIVE_ERROR_PREFIX DEEPDIVE_PROGRESS_FD DEEPDIVE_APP APP_HOME
eval 'bash -veu "$runDir"/plan.sh '$DEEPDIVE_PROGRESS_FD'>&2 2>&1' |
# keep a log with timestamps
ts "%F %H:%M:%.S $HOSTNAME" | tee "$runDir"/log.txt
