#!/usr/bin/env bash
# reset_timestamp -- Resets timestamp files by putting them aside
# > reset_timestamp TIMESTAMP_FILE...
##
set -eu

: ${DEEPDIVE_LOG_LEVEL:=1}

verboseLevel2=; [[ $DEEPDIVE_LOG_LEVEL -lt 2 ]] || verboseLevel2=v

for ts in "$@"; do
    [[ -e "$ts" ]] || continue
    mv -f$verboseLevel2 --no-target-directory "$ts" "$ts~"
done
