#!/usr/bin/env bash
# restore_timestamp -- Restores timestamp files prior to the previous reset
# > restore_timestamp TIMESTAMP_FILE...
##
set -eu

for ts in "$@"; do
    [[ -e "$ts~" ]] || continue
    mv -v -f --no-target-directory "$ts~" "$ts"
done
