#!/usr/bin/env bash
# restore_timestamp -- Restores timestamp files prior to the previous reset
# > restore_timestamp TIMESTAMP_FILE...
##
set -eu

: ${DEEPDIVE_LOG_LEVEL:=1}

verboseLevel2=; [[ $DEEPDIVE_LOG_LEVEL -lt 2 ]] || verboseLevel2=v

for ts in "$@"; do
    [[ -e "$ts~" ]] || continue
    mv -f$verboseLevel2 --no-target-directory "$ts~" "$ts"
done
