#!/usr/bin/env bash
# db-init -- Initializes PostgreSQL database for a DeepDive application
# > eval "$(db-parse "$url")"
# > db-init
##
set -eu

{
mysqladmin -h $DBHOST -P $DBPORT -u $DBUSER --password="$DBPASSWORD" -f drop   $DBNAME || true
mysqladmin -h $DBHOST -P $DBPORT -u $DBUSER --password="$DBPASSWORD" -f create $DBNAME
} >/dev/null
