#!/usr/bin/env bash
# db-parse -- Parses URL for MySQL database set up for a DeepDive application
# > db-parse "$url"
set -eu

. parse-url.sh "$@"

# default values
: ${user:=$USER} ${port:=3306}

# map to environment variables for mysql
echo "DBTYPE=mysql"
echo "DBVARIANT=${dbtype}"
echo "DBHOST=${host}"
echo "DBPORT=${port}"
echo "DBUSER=${user}"
echo "DBPASSWORD=${password}"
echo "DBNAME=${dbname}"
echo "export DBHOST DBPORT DBUSER DBPASSWORD DBNAME"

# more variables for Scala application.conf
echo "DEEPDIVE_JDBC_DRIVER=com.mysql.jdbc.Driver"
echo "DEEPDIVE_JDBC_URL=jdbc:mysql://$host${port:+:$port}/$dbname"
echo "export DEEPDIVE_JDBC_DRIVER DEEPDIVE_JDBC_URL"
