#!/usr/bin/env bash
# db-create-table -- Creates a table from its definition, coping with existing ones
# $ export CREATE_TABLE_TYPE=... CREATE_TABLE_EXTRA_CLAUSES=...
# $ export CREATE_IF_NOT_EXISTS=1
# $ export DROP_VIEW_TYPE=... DROP_TABLE_TYPE=...
# $ db-create-table TABLE TABLE_DEFINITION_SQL
##
set -euo pipefail

: ${CREATE_TABLE_TYPE:=} ${CREATE_TABLE_EXTRA_CLAUSES:=}
: ${CREATE_IF_NOT_EXISTS:=}
: ${DROP_VIEW_TYPE:=} ${DROP_TABLE_TYPE:=}

[[ $# -gt 0 ]] || usage "$0" "Missing TABLE name"
Table=$1; shift
[[ $# -gt 0 ]] || usage "$0" "Missing TABLE_DEFINITION_SQL"
TableDef=$1; shift

# Greenplum does not have CREATE TABLE IF NOT EXISTS, hence the following workaround
if [[ -n $CREATE_IF_NOT_EXISTS ]]; then
    ! db-execute "\\d $Table" &>/dev/null || exit 0
else
    db-execute "DROP $DROP_VIEW_TYPE  VIEW  $Table CASCADE" &>/dev/null || true
    db-execute "DROP $DROP_TABLE_TYPE TABLE $Table CASCADE" &>/dev/null || true
fi
# make sure JSON SQL TYPE (or DOMAIN) is available for TSJ
[[ $(db-execute '\dT JSON' --tuples-only --no-align | wc -l) -gt 0 ]] || db-execute "CREATE DOMAIN JSON AS TEXT;" || true
exec db-execute "CREATE $CREATE_TABLE_TYPE TABLE $Table $TableDef $CREATE_TABLE_EXTRA_CLAUSES"
